---
version: "3"

services:
  syncthing:
    image: syncthing/syncthing:1.28
    container_name: syncthing
    restart: always
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    environment:
      - PUID=${HOST_UID}
      - PGID=${HOST_GID}
    volumes:
      - ~/.config/syncthing:/var/syncthing/config
      - ~/Documents/syncthing:/var/syncthing/data

