#!/bin/bash

FILE_LOCATION=$(dirname $(readlink -f "$0"))
DOCKER_COMPOSE_PATH="$FILE_LOCATION/docker-compose.yaml"

mkdir -p ~$XDG_CONFIG_HOME/syncthing
mkdir -p ~/Documents/syncthing

export HOST_UID=$(id -u) HOST_GID=$(id -g)
docker compose -f $DOCKER_COMPOSE_PATH up -d

