# terminal settings
set -g default-terminal "tmux-256color"
# window split
bind-key v split-window -h
bind-key s split-window -v
# vim style pane resize
bind -n M-k resize-pane -U 5
bind -n M-j resize-pane -D 5
bind -n M-h resize-pane -L 5
bind -n M-l resize-pane -R 5
# vim style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# mouse support
set -g mouse on
# start window numbering from 1
set -g base-index 1
# enable vi mode
setw -g mode-keys vi
# remap copy paste keys
bind P paste-buffer
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection
# scroll with alt+arrow keys
bind -n M-Up copy-mode \; send-keys -X -N 5 scroll-up
bind -n M-Down copy-mode \; send-keys -X -N 5 scroll-down
# scroll with alt+,/. (alternative)
bind -n M-, copy-mode \; send-keys -X -N 5 scroll-up
bind -n M-. copy-mode \; send-keys -X -N 5 scroll-down
# config reload
bind r source-file ~/.config/tmux/tmux.conf \; display-message "~/.config/tmux/tmux.conf reloaded"
# color scheme
source-file ~/.config/tmux/tmux-gruvbox-dark.conf
# plugins
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dominikduda/tmux_mode_indicator'
# tmux_mode_indicator settings
set -g @tmux_mode_indicator_left_edge_character ""
set -g @tmux_mode_indicator_separator "+"
set -g @tmux_mode_indicator_background "colour124"
set -g @tmux_mode_indicator_right_edge_character_fg "colour214"
set -g @tmux_mode_indicator_left_edge_character_bg "colour239"
# plugin manager
set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.config/tmux/plugins/"
run -b '~/.config/tmux/plugins/tpm/tpm'
