#!/bin/sh

PINENTRY_DMENU=
if [ -x "$(command dmenu)" ] && [ -x "$(command dmenu-pinentry)" ]; then
    PINENTRY_DMENU=1
fi

case $PINENTRY_CMD in
    dmenu)
        [ $PINENTRY_DMENU -eq 1 ] && exec dmenu-pinentry ;;
    tty|*)
        exec pinentry-tty ;;
esac
