# locale
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export EDITOR=nvim
# custom programs and scripts
export PATH="$PATH":~/.local/bin
# XDG directories
export XDG_CONFIG_HOME=~/.config
export XDG_CACHE_HOME=~/.cache
export XDG_DATA_HOME=~/.local/share
# dotfiles sources location
export DOTFILES_SRC_DIR=~/.local/src/dotfiles
# bash local location
export BASH_LOCAL_DIR="$XDG_CONFIG_HOME"/bash

[ -f "$BASH_LOCAL_DIR"/local.profile ] && . "$BASH_LOCAL_DIR"/local.profile
[ -f ~/.bashrc ] && . ~/.bashrc
