#!/bin/sh

DOCKER_COMPOSE_PATH="$XDG_CONFIG_HOME/syncthing/docker-compose.yaml"
RUNTIME="docker"
if [ -x "$(command -v podman)" ]; then
    RUNTIME="podman"
fi

$RUNTIME compose -f $DOCKER_COMPOSE_PATH down
