# programs
export EDITOR=nvim
# custom programs and scripts
export PATH="$PATH":~/.local/bin
# XDG directories
export XDG_CONFIG_HOME=~/.config
export XDG_CACHE_HOME=~/.cache
export XDG_DATA_HOME=~/.local/share
# dotfiles sources location
export DOTFILES_SRC_DIR=~/.local/src/dotfiles

[ -f ~/.bashrc ] && . ~/.bashrc
