#
# ~/.bash_profile
#

# programs
export EDITOR=nvim

# XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# rustup
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"

[[ -f ~/.bashrc ]] && . ~/.bashrc

