# Vim
alias vi="nvim"
alias vim="nvim"
alias vimdiff="nvim -d"

# TODO: move to script/minimal
reload_dotfiles() {
    CURRENT_PWD=$(pwd)
    cd $DOTFILES_SRC_DIR \
        && git pull --rebase \
        && SKIP_PKG=1 ./install \
        && . ~/.bashrc \
        cd $CURRENT_PWD
}

# misc
alias ls='ls --color=auto'
alias grep='grep --color=auto'
