# vim (neovim)
alias vi="nvim"
alias vim="nvim"
alias vimdiff="nvim -d"
# misc
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias bc='bc -l'

[ -f "$BASH_LOCAL_DIR"/local.aliases ] && . "$BASH_LOCAL_DIR"/local.aliases
