# programs
export EDITOR=nvim
# custom programs and scripts
export PATH="$PATH":~/.local/bin
# XDG directories
export XDG_CONFIG_HOME=~/.config
export XDG_CACHE_HOME=~/.cache
export XDG_DATA_HOME=~/.local/share
# dotfiles sources location
export DOTFILES_SRC_DIR=~/.local/src/dotfiles
# agents
export CODEX_HOME="$XDG_CONFIG_HOME"/codex
export CLAUDE_CONFIG_DIR="$XDG_CONFIG_HOME"/claude
# rust
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export CARGO_HOME="$XDG_DATA_HOME"/cargo
# go
export GOPATH="$XDG_DATA_HOME"/go
export GOMODCACHE="$XDG_CACHE_HOME"/go/mod
# pnpm
export PNPM_HOME="$XDG_DATA_HOME"/pnpm
export PATH=$PATH:"$PNPM_HOME"
# clojure
export LEIN_HOME="$XDG_DATA_HOME"/lein

[ -f ~/.bashrc ] && . ~/.bashrc
